# Generated by Django 6.0.7 on 2026-08-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="título"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ubicación"
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(verbose_name="fecha y hora de inicio"),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="fecha y hora de fin",
                    ),
                ),
                (
                    "recurring_group",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="grupo recurrente",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado en"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ("start_at",),
            },
        ),
        migrations.CreateModel(
            name="Confirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="confirmado en"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="calendario.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmación",
                "verbose_name_plural": "confirmaciones",
                "ordering": ("event__start_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event"),
                        name="unique_confirmation_per_user_and_event",
                    )
                ],
            },
        ),
    ]
