# Generated by Django 6.0.7 on 2026-08-13 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="título"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ubicación"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(verbose_name="fecha y hora de inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="fecha y hora de fin",
                    ),
                ),
                (
                    "grupo_recurrente",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="grupo recurrente",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creado en"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ("fecha_inicio",),
            },
        ),
        migrations.CreateModel(
            name="Confirmacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="confirmado en"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmaciones",
                        to="calendario.evento",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmación",
                "verbose_name_plural": "confirmaciones",
                "ordering": ("evento__fecha_inicio",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "evento"),
                        name="unica_confirmacion_por_usuario_y_evento",
                    )
                ],
            },
        ),
    ]
