# Generated by Django 6.0.7 on 2026-09-02 13:38

from django.db import migrations, models

import calendario.validators


class Migration(migrations.Migration):
    dependencies = [
        ("calendario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                validators=[calendario.validators.validate_meeting_link_domain],
                verbose_name="enlace de reunión virtual",
            ),
        ),
    ]
