# Generated by Django 6.0.7 on 2026-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="house_number",
            field=models.CharField(
                default="", max_length=20, verbose_name="número de casa"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="número de teléfono"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.CharField(
                default="", max_length=200, verbose_name="calle"
            ),
            preserve_default=False,
        ),
    ]
