# Generated by Django 6.0.7 on 2026-08-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_house_number_user_phone_number_user_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="house_number",
            field=models.CharField(
                max_length=20,
                verbose_name="número de casa (+ apartamento, si aplica)",
            ),
        ),
    ]
